
name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Update Spec
        run: |
          postman collection run 16863310-1fad0d33-3f01-44e3-9be2-5086810bc309 -i 16863310-2bb2eb1f-35a3-4d39-afb2-7db04ccddaca --environment 16863310-7dc8d888-f177-4036-9ae0-f2e51f2efb76
