
name: Update My Spec

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.{yaml,yml,json}'  # Trigger on changes to Swagger/OpenAPI files
jobs:
  update-postman-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update Postman Specification
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_WORKSPACE_ID: ${{ secrets.POSTMAN_WORKSPACE_ID }}
          POSTMAN_SPEC_ID: ${{ secrets.POSTMAN_SPEC_ID }}
        run: |
          # Install Postman CLI
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          SPEC_CONTENT=$(curl -s -H "Authorization: token ${GH_TOKEN}" \https://raw.githubusercontent.com/aamir-ahmed/Products-and-Orders/blob/master/Products-and-orders.yaml \| sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}')

          # Update the specification in Postman
          curl --location --request PATCH "https://api.getpostman.com/specs/7d1c97c7-cfdd-4994-b3f3-f25142da57b5/files/index.yaml" \--header "Content-Type: application/json" \--header "X-API-Key: ${POSTMAN_API_KEY}" \--data "{\"content\": \"$SPEC_CONTENT\"}"
